services:
  postgresql:
    container_name: postgresql-library
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: library-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - library

  liquibase-migrations:
    container_name: library-db-migrations
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --search-path=/liquibase/changelog/
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/library-db
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - library

volumes:
  postgresql: { }

networks:
  library: { }