spring:
  application:
    name: petLibrary

  datasource:
    url: jdbc:postgresql://localhost:5434/library-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080